//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("sdescript ver:0.9.31101.1")]
[assembly: AssemblyDescription("sdescript")]
[assembly: AssemblyProduct("sdescript")]
[assembly: AssemblyCopyright("Copyright (C) 2003-2013 Kody Brown.")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("A6B472E3-EEF4-4C62-95B2-E0834BA7B9BB")]
[assembly: AssemblyVersion("0.9.31101.1")]
[assembly: AssemblyFileVersion("0.9.31101.1")]


